Тест на то что execute метод выкидывает исключение.
yapro/doctrine-understanding pull request #2
Opened 2021-10-29 11:43 UTC by smamykin

2021-11-01 08:52 UTC, yapro requested changes

2021-11-01 08:52 UTC, yapro commented on tests/Functional/AllTest.php
> +            ->andWhere('a.title = :oldTitle')
почему не воспользоваться id-кой ? будет ведь читаемей, я честно говоря немного запутался с этими тайтлами

2021-11-01 08:52 UTC, yapro commented on tests/Functional/AllTest.php
> +        self::$entityManager->getConnection()->executeQuery("PRAGMA foreign_keys = ON");
предлагаю это добавить в место создания подключения https://github.com/yapro/doctrine-understanding/blob/master/tests/Functional/CommonTestCase.php#L54

2021-11-01 08:52 UTC, yapro commented on tests/Functional/AllTest.php
> +        self::$entityManager->persist($child);
кажется можно не персистить, он автоматом персистится

2021-11-01 08:52 UTC, yapro commented on tests/Functional/AllTest.php
> +        $articleRepository = self::$entityManager->getRepository(Article::class);
переменная используется 1 раз, значит нет смысла использовать

2021-11-01 08:52 UTC, yapro commented on tests/Functional/AllTest.php
> +        $articleRepository = self::$entityManager->getRepository(Article::class);
переменная используется 1 раз, значит нет смысла использовать

2021-11-01 11:02 UTC, smamykin commented on tests/Functional/AllTest.php
> +        self::$entityManager->getConnection()->executeQuery("PRAGMA foreign_keys = ON");
Попробовал. вот здесь можно посмотреть что получилось: https://github.com/yapro/doctrine-understanding/compare/feature/executeThrowsException...feature/executeThrowsException_try?expand=1

Что-то больно сложно получается. При дропе схемы должны учитсываться forigin key'и, но они почему то не учитваются. Я покопал немного и решил оставить.

2021-11-01 14:21 UTC, yapro commented on tests/Functional/AllTest.php
> +        self::$entityManager->getConnection()->executeQuery("PRAGMA foreign_keys = ON");
Понятно, значит текущие тесты написаны без учета проверок FK, получается что надо просто текущие тесты поправить, т.е. там где удаление происходит неявное, надо делать дополнительное явное удаление. Подскажи пожалуйста, как лучше, замержить или сначала поправим тесты по тобой указанной ссылке

2021-11-01 15:04 UTC, smamykin commented on tests/Functional/AllTest.php
> +        self::$entityManager->getConnection()->executeQuery("PRAGMA foreign_keys = ON");
Там только один тест валится по этой причине - и его не долго поправить. Больший вопрос возникает при dropSchemа

2021-11-02 07:02 UTC, yapro commented on tests/Functional/AllTest.php
> +        self::assertSame(1, $orphanRemovalFalse->getId());
а разве до этой строки дойдет дело? я думал при флаше будет эксепшен

2021-11-02 07:04 UTC, yapro commented on tests/Functional/CommonTestCase.php
> +            self::$entityManager->getClassMetadata(Article::class),
а почему передвинул вниз? ты вроде при удалении отключаешь FK

2021-11-02 07:25 UTC, smamykin commented on tests/Functional/AllTest.php
> +        self::assertSame(1, $orphanRemovalFalse->getId());
Да, действительно, просто забыл удалить эту строку - удалил теперь.

2021-11-02 07:26 UTC, smamykin commented on tests/Functional/CommonTestCase.php
> +            self::$entityManager->getClassMetadata(Article::class),
Откатил изменения по этому моменту.

2021-11-02 07:37 UTC, yapro commented on tests/Functional/CommonTestCase.php
> +            $sql .= 'PRAGMA foreign_keys = OFF;';
наверное эту инструкцию можно поместить перед форычем

2021-11-02 07:37 UTC, yapro commented on tests/Functional/CommonTestCase.php
> +            $sql .= 'PRAGMA foreign_keys = ON;';
наверное эту инструкцию можно расположить после форыча

2021-11-02 08:42 UTC, merged